- type: job
  id: HeadOfPersonnel
  name: job-name-hop
  description: job-description-hop
  playTimeTracker: JobHeadOfPersonnel
  weight: 10
  startingGear: HoPGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security # NoooOoOo!! My HoPcurity!1
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  - Boxer # DeltaV - Add Boxer access
  - Clown # DeltaV - Add Clown access
  - Library # DeltaV - Add Library access
  - Mime # DeltaV - Add Mime access
  - Musician # DeltaV - Add Musician access
  - Reporter # DeltaV - Add Reporter access
  - Zookeeper # DeltaV - Add Zookeeper access
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddComponentSpecial
    components:
    - type: PsionicBonusChance #Nyano - Summary: makes it more likely to become psionic.
      flatBonus: 0.025

- type: startingGear
  id: HoPGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpackHOPFilled
    shoes: ClothingShoesLeather # DeltaV - HoP needs something better than plebe shoes.
    head: ClothingHeadHatHopcap
    id: HoPPDA
    gloves: ClothingHandsGlovesHop
    ears: ClothingHeadsetHoP # DeltaV - HoP is now a service role, replaces their all channels headset.
    belt: BoxFolderClipboard
  innerClothingSkirt: ClothingUniformJumpskirtHoP
  satchel: ClothingBackpackSatchelHOPFilled
  duffelbag: ClothingBackpackDuffelHOPFilled
