# Uniforms
- type: loadout
  id: LoadoutSecurityUniformJumpsuitBlue
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingUniformJumpsuitSecBlue

- type: loadout
  id: LoadoutSecurityUniformJumpsuitGrey
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingUniformJumpsuitSecGrey

- type: loadout
  id: LoadoutSecurityUniformJumpskirtGrey
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingUniformJumpskirtSecGrey

- type: loadout
  id: LoadoutSecurityUniformJumpskirtBlue
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingUniformJumpskirtSecBlue

- type: loadout
  id: LoadoutUniformJumpsuitWardenBlue
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Warden
  items:
    - ClothingUniformJumpsuitWardenBlue

- type: loadout
  id: LoadoutUniformJumpsuitWardenGrey
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Warden
  items:
    - ClothingUniformJumpsuitWardenGrey

- type: loadout
  id: LoadoutUniformJumpskirtWardenBlue
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Warden
  items:
    - ClothingUniformJumpskirtWardenBlue

- type: loadout
  id: LoadoutUniformJumpskirtWardenGrey
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Warden
  items:
    - ClothingUniformJumpskirtWardenGrey

- type: loadout
  id: LoadoutUniformJumpskirtHoSBlue
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsSecurity
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHoSBlue

- type: loadout
  id: LoadoutUniformJumpskirtHoSGrey
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsSecurity
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHoSGrey

- type: loadout
  id: LoadoutUniformJumpsuitSecFormal
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingUniformJumpsuitSecFormal

- type: loadout
  id: LoadoutUniformJumpsuitSecSummer
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingUniformJumpsuitSecSummer

# Mask
- type: loadout
  id: LoadoutSecurityMaskGasSwat
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMaskSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Warden
        - HeadOfSecurity
  items:
    - ClothingMaskGasSwat

# Shoes
- type: loadout
  id: LoadoutSecurityShoesJackboots
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutShoesSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingShoesBootsJack

- type: loadout
  id: LoadoutClothingShoesBootsCombat
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutShoesSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingShoesBootsCombatFilled

# Eyes
- type: loadout
  id: LoadoutSecurityEyesHudSecurity
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutEyesSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingEyesHudSecurity

- type: loadout
  id: ClothingEyesGlassesSunglasses
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutEyesSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingEyesGlassesSunglasses

- type: loadout
  id: LoadoutSecurityEyesEyepatchHudSecurity
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutEyesSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingEyesEyepatchHudSecurity

- type: loadout
  id: LoadoutSecurityEyesHudSecurityPrescription
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutEyesSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
    - !type:CharacterTraitRequirement
      traits:
        - Nearsighted
  items:
    - ClothingEyesPrescriptionHudSecurity

- type: loadout
  id: LoadoutClothingEyesGlassesSecurity
  category: JobsSecurity
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutEyesSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingEyesGlassesSecurity

#Backpack
- type: loadout
  id: LoadoutClothingBackSecurity
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutBackSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingBackpackSecurity

- type: loadout
  id: LoadoutClothingBackSecuritySatchel
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutBackSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingBackpackSatchelSecurity

- type: loadout
  id: LoadoutClothingBackSecurityDuffel
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutBackSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingBackpackDuffelSecurity

# Head
- type: loadout
  id: LoadoutSecurityHeadHatBeret
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingHeadHatBeretSecurity

- type: loadout
  id: LoadoutClothingHeadHelmetBasic
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingHeadHelmetBasic

- type: loadout
  id: LoadoutClothingHeadHatBeretBrigmedic
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Brigmedic
  items:
    - ClothingHeadHatBeretBrigmedic

- type: loadout
  id: LoadoutClothingHeadHatBeretCorpsman
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Brigmedic
  items:
    - ClothingHeadHatBeretCorpsman

- type: loadout
  id: LoadoutClothingHeadHatBeretWarden
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Warden
  items:
    - ClothingHeadHatBeretWarden

- type: loadout
  id: LoadoutClothingHeadHatBeretHoS
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadSecurity
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingHeadHatBeretHoS

- type: loadout
  id: LoadoutSecurityHeadHelmetInsulated
  category: JobsSecurity
  cost: 1
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutHeadSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingHeadHelmetInsulated

# Belt
- type: loadout
  id: LoadoutSecurityBeltWebbing
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutBeltSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingBeltSecurityWebbingFilled

- type: loadout
  id: LoadoutClothingBeltCorpsmanWebbing
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutBeltSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Brigmedic
  items:
    - ClothingBeltCorpsmanWebbingFilled

- type: loadout
  id: LoadoutClothingBeltSecurity
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutBeltSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingBeltSecurityFilled

- type: loadout
  id: LoadoutClothingBeltHolster
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutBeltSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingBeltHolster

#Gloves

- type: loadout
  id: LoadoutClothingHandsGlovesNitrile
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutGlovesSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Brigmedic
  items:
    - ClothingHandsGlovesNitrile

# Outerwear

- type: loadout
  id: LoadoutClothingOuterArmorPlateCarrier
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutOuterSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingOuterArmorPlateCarrier

- type: loadout
  id: LoadoutClothingOuterArmorDuraVest
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutOuterSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingOuterArmorDuraVest

- type: loadout
  id: LoadoutClothingOuterArmorBasic
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutOuterSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingOuterArmorBasic

- type: loadout
  id: LoadoutClothingOuterArmorSlim
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutOuterSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - ClothingOuterArmorBasicSlim

- type: loadout
  id: LoadoutClothingOuterCoatDetective
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutOuterSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Detective
  items:
    - ClothingOuterCoatDetective

- type: loadout
  id: LoadoutOuterVestDetective
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutOuterSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Detective
  items:
    - ClothingOuterVestDetective

- type: loadout
  id: LoadoutClothingOuterCoatWarden
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutOuterSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Warden
  items:
    - ClothingOuterCoatWarden

- type: loadout
  id: LoadoutClothingOuterCoatHoSTrench
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutOuterSecurity
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingOuterCoatHoSTrench

- type: loadout
  id: LoadoutClothingOuterWinterHoS
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutOuterSecurity
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingOuterWinterHoS

# Neck
- type: loadout
  id: LoadoutClothingNeckCloakHos
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutNeckSecurity
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingNeckCloakHos

- type: loadout
  id: LoadoutClothingNeckMantleHOS
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutNeckSecurity
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingNeckMantleHOS

- type: loadout
  id: LoadoutBedsheetBrigmedic
  category: JobsSecurity
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutNeckSecurity
    - !type:CharacterJobRequirement
      jobs:
        - Brigmedic
  items:
    - BedsheetBrigmedic

# Equipment, limit 3 selections
# Duplicate "Spare" equipment exists and shares the ItemGroup, for those officers who like to pack a spare magazine in their pocket, outside of what was issued to them.
# I knew a lot of people in my time working IRL Armed security that did this.
- type: loadout
  id: LoadoutSecurityCombatKnife
  category: JobsSecurity
  cost: 0
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutEquipmentSecurity
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - CombatKnife

- type: loadout
  id: LoadoutSecurityFlash
  category: JobsSecurity
  cost: 0
  requirements:
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - Flash
