contact_links:
  - name: Сообщить об уязвимости
    url: https://github.com/Lost-Paradise-Project/Lost-Paradise/blob/master/SECURITY.md
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности.
  - name: Предложение
    url: https://wiki.lost-paradise.space/discord
    about: Свои предложения можете оставлять в соответствующем канале Discord.
