- type: playTimeTracker
  id: JobLPPBlueShieldOfficer

- type: playTimeTracker
  id: JobLPP–êdjutant

- type: playTimeTracker
  id: LPPCentralCommandRepresentative

- type: playTimeTracker
  id: JobCentralCommandRepresentative

- type: playTimeTracker
  id: JobPilot

- type: playTimeTracker
  id: LPPJobSecurityEnginer