# Base dungeon prototypes
- type: dungeonConfig
  id: LPPEverything
  generator: !type:PrefabDunGen
    roomWhitelist:
      - CaveFactory
      - LPPLavaBrig
      - LPPLavaMercenary
      - LPPSalvageExperiment
      - LPPVirologyLab
      - LPPSalvageOutpost
    presets:
      - Bucket
      - Wow
      - SpaceShip
      - Tall
  postGeneration:
    - !type:CorridorPostGen
      width: 3

    - !type:DungeonEntrancePostGen
      count: 2

    - !type:RoomEntrancePostGen
      entities:
        - CableApcExtension
        - AirlockGlass

    - !type:EntranceFlankPostGen
      entities:
        - Grille
        - Window

    - !type:ExternalWindowPostGen
      entities:
        - Grille
        - Window

    - !type:WallMountPostGen
      spawns:
        - id: RandomPosterLegit
          orGroup: content
        - id: ExtinguisherCabinetFilled
          prob: 0.2
          orGroup: content
        - id: RandomPainting
          prob: 0.05
          orGroup: content
        - id: DefibrillatorCabinetFilled
          prob: 0.1
          orGroup: content

    - !type:BoundaryWallPostGen
      tile: FloorSteel
      wall: WallSolid
      cornerWall: WallReinforced

    - !type:JunctionPostGen
      width: 1

    - !type:JunctionPostGen

    - !type:AutoCablingPostGen

    - !type:CornerClutterPostGen
      contents:
        - id: PottedPlantRandom
          amount: 1
    - !type:CorridorDecalSkirtingPostGen
      color: "#D381C996"
      cardinalDecals:
        South: BrickTileWhiteLineS
        East: BrickTileWhiteLineE
        North: BrickTileWhiteLineN
        West: BrickTileWhiteLineW
      cornerDecals:
        SouthEast: BrickTileWhiteCornerSe
        SouthWest: BrickTileWhiteCornerSw
        NorthEast: BrickTileWhiteCornerNe
        NorthWest: BrickTileWhiteCornerNw
      pocketDecals:
        SouthWest: BrickTileWhiteInnerSw
        SouthEast: BrickTileWhiteInnerSe
        NorthWest: BrickTileWhiteInnerNw
        NorthEast: BrickTileWhiteInnerNe

# CaveFactory prototypes
- type: dungeonConfig
  id: LPPCaveFactory
  generator: !type:PrefabDunGen
    roomWhitelist:
      - LPPCaveFactory
    presets:
      - Bucket
      - Wow
      - SpaceShip
      - Tall
  postGeneration:
    - !type:CorridorPostGen
      width: 3

    - !type:DungeonEntrancePostGen
      count: 2

    - !type:RoomEntrancePostGen
      entities:
        - CableApcExtension
        - AirlockGlass

    - !type:EntranceFlankPostGen
      entities:
        - Grille
        - Window

    - !type:ExternalWindowPostGen
      entities:
        - Grille
        - Window

    - !type:WallMountPostGen
      spawns:
        - id: RandomPosterLegit
          orGroup: content
        - id: ExtinguisherCabinetFilled
          prob: 0.2
          orGroup: content
        - id: RandomPainting
          prob: 0.05
          orGroup: content

    - !type:BoundaryWallPostGen
      tile: FloorSteel
      wall: WallSolid
      cornerWall: WallReinforced

    - !type:JunctionPostGen
      width: 1

    - !type:JunctionPostGen

    - !type:AutoCablingPostGen

    - !type:CornerClutterPostGen
      contents:
        - id: PottedPlantRandom
          amount: 1
    - !type:CorridorDecalSkirtingPostGen
      color: "#ffa64d96"
      cardinalDecals:
        South: BrickTileWhiteLineS
        East: BrickTileWhiteLineE
        North: BrickTileWhiteLineN
        West: BrickTileWhiteLineW
      cornerDecals:
        SouthEast: BrickTileWhiteCornerSe
        SouthWest: BrickTileWhiteCornerSw
        NorthEast: BrickTileWhiteCornerNe
        NorthWest: BrickTileWhiteCornerNw
      pocketDecals:
        SouthWest: BrickTileWhiteInnerSw
        SouthEast: BrickTileWhiteInnerSe
        NorthWest: BrickTileWhiteInnerNw
        NorthEast: BrickTileWhiteInnerNe

# MedSci prototypes
- type: dungeonConfig
  id: LPPMedSci
  generator: !type:PrefabDunGen
    roomWhitelist:
      - LPPSalvageExperiment
    presets:
      - Bucket
      - Wow
      - SpaceShip
      - Tall
  postGeneration:
    - !type:CorridorPostGen
      width: 3

    - !type:DungeonEntrancePostGen
      count: 2

    - !type:RoomEntrancePostGen
      entities:
        - CableApcExtension
        - AirlockGlass

    - !type:EntranceFlankPostGen
      entities:
        - Grille
        - Window

    - !type:ExternalWindowPostGen
      entities:
        - Grille
        - Window

    - !type:WallMountPostGen
      spawns:
        - id: RandomPosterLegit
          orGroup: content
        - id: ExtinguisherCabinetFilled
          prob: 0.2
          orGroup: content
        - id: RandomPainting
          prob: 0.05
          orGroup: content
        - id: DefibrillatorCabinetFilled
          prob: 0.2
          orGroup: content

    - !type:BoundaryWallPostGen
      tile: FloorSteel
      wall: WallSolid
      cornerWall: WallReinforced

    - !type:JunctionPostGen
      width: 1

    - !type:JunctionPostGen

    - !type:AutoCablingPostGen

    - !type:CornerClutterPostGen
      contents:
        - id: PottedPlantRandom
          amount: 1
    - !type:CorridorDecalSkirtingPostGen
      color: "#D381C996"
      cardinalDecals:
        South: BrickTileWhiteLineS
        East: BrickTileWhiteLineE
        North: BrickTileWhiteLineN
        West: BrickTileWhiteLineW
      cornerDecals:
        SouthEast: BrickTileWhiteCornerSe
        SouthWest: BrickTileWhiteCornerSw
        NorthEast: BrickTileWhiteCornerNe
        NorthWest: BrickTileWhiteCornerNw
      pocketDecals:
        SouthWest: BrickTileWhiteInnerSw
        SouthEast: BrickTileWhiteInnerSe
        NorthWest: BrickTileWhiteInnerNw
        NorthEast: BrickTileWhiteInnerNe

# FactoryDorms prototypes
- type: dungeonConfig
  id: LPPFactoryDorms
  generator: !type:PrefabDunGen
    roomWhitelist:
      - LPPCaveFactory
    presets:
      - Bucket
      - Wow
      - SpaceShip
      - Tall
  postGeneration:
    - !type:CorridorPostGen
      width: 3

    - !type:DungeonEntrancePostGen
      count: 2

    - !type:RoomEntrancePostGen
      entities:
        - CableApcExtension
        - AirlockGlass

    - !type:EntranceFlankPostGen
      entities:
        - Grille
        - Window

    - !type:ExternalWindowPostGen
      entities:
        - Grille
        - Window

    - !type:WallMountPostGen
      spawns:
        - id: RandomPosterLegit
          orGroup: content
        - id: ExtinguisherCabinetFilled
          prob: 0.2
          orGroup: content
        - id: RandomPainting
          prob: 0.05
          orGroup: content
        - id: DefibrillatorCabinetFilled
          prob: 0.2
          orGroup: content

    - !type:BoundaryWallPostGen
      tile: FloorSteel
      wall: WallSolid
      cornerWall: WallReinforced

    - !type:JunctionPostGen
      width: 1

    - !type:JunctionPostGen

    - !type:AutoCablingPostGen

    - !type:CornerClutterPostGen
      contents:
        - id: PottedPlantRandom
          amount: 1
    - !type:CorridorDecalSkirtingPostGen
      color: "#D381C996"
      cardinalDecals:
        South: BrickTileWhiteLineS
        East: BrickTileWhiteLineE
        North: BrickTileWhiteLineN
        West: BrickTileWhiteLineW
      cornerDecals:
        SouthEast: BrickTileWhiteCornerSe
        SouthWest: BrickTileWhiteCornerSw
        NorthEast: BrickTileWhiteCornerNe
        NorthWest: BrickTileWhiteCornerNw
      pocketDecals:
        SouthWest: BrickTileWhiteInnerSw
        SouthEast: BrickTileWhiteInnerSe
        NorthWest: BrickTileWhiteInnerNw
        NorthEast: BrickTileWhiteInnerNe

# LavaMercenary prototypes
- type: dungeonConfig
  id: LPPLavaMercenary
  generator: !type:PrefabDunGen
    roomWhitelist:
      - LPPLavaMercenary
    presets:
      - Bucket
      - Wow
      - SpaceShip
      - Tall
  postGeneration:
    - !type:CorridorPostGen
      width: 3

    - !type:DungeonEntrancePostGen
      count: 2

    - !type:RoomEntrancePostGen
      entities:
        - CableApcExtension
        - AirlockMercenaryGlassDungeon

    - !type:EntranceFlankPostGen
      entities:
        - Grille
        - Window

    - !type:ExternalWindowPostGen
      entities:
        - Grille
        - Window

    - !type:WallMountPostGen
      spawns:
        - id: RandomPosterContraband
          orGroup: content
        - id: ExtinguisherCabinetFilled
          prob: 0.2
          orGroup: content
        - id: RandomPainting
          prob: 0.05
          orGroup: content

    - !type:BoundaryWallPostGen
      tile: FloorSteel
      wall: WallSolid
      cornerWall: WallReinforced

    - !type:JunctionPostGen
      width: 1

    - !type:JunctionPostGen

    - !type:AutoCablingPostGen

    - !type:CornerClutterPostGen
      contents:
        - id: PottedPlantRandom
          amount: 1
    - !type:CorridorDecalSkirtingPostGen
      color: "#5E7C16"
      cardinalDecals:
        South: BrickTileWhiteLineS
        East: BrickTileWhiteLineE
        North: BrickTileWhiteLineN
        West: BrickTileWhiteLineW
      cornerDecals:
        SouthEast: BrickTileWhiteCornerSe
        SouthWest: BrickTileWhiteCornerSw
        NorthEast: BrickTileWhiteCornerNe
        NorthWest: BrickTileWhiteCornerNw
      pocketDecals:
        SouthWest: BrickTileWhiteInnerSw
        SouthEast: BrickTileWhiteInnerSe
        NorthWest: BrickTileWhiteInnerNw
        NorthEast: BrickTileWhiteInnerNe

# VirologyLab prototypes
- type: dungeonConfig
  id: LPPVirologyLab
  generator: !type:PrefabDunGen
    roomWhitelist:
      - LPPVirologyLab
    presets:
      - Bucket
      - Wow
      - SpaceShip
      - Tall
  postGeneration:
    - !type:CorridorPostGen
      width: 3

    - !type:DungeonEntrancePostGen
      count: 2

    - !type:RoomEntrancePostGen
      entities:
        - CableApcExtension
        - AirlockVirologyGlassDungeon

    - !type:EntranceFlankPostGen
      entities:
        - Grille
        - Window

    - !type:ExternalWindowPostGen
      entities:
        - Grille
        - Window

    - !type:WallMountPostGen
      spawns:
        - id: RandomPosterLegit
          orGroup: content
        - id: ExtinguisherCabinetFilled
          prob: 0.2
          orGroup: content
        - id: RandomPainting
          prob: 0.05
          orGroup: content
        - id: DefibrillatorCabinetFilled
          prob: 0.1
          orGroup: content

    - !type:BoundaryWallPostGen
      tile: FloorSteel
      wall: WallSolid
      cornerWall: WallReinforced

    - !type:JunctionPostGen
      width: 1

    - !type:JunctionPostGen

    - !type:AutoCablingPostGen

    - !type:CornerClutterPostGen
      contents:
        - id: PottedPlantRandom
          amount: 1
    - !type:CorridorDecalSkirtingPostGen
      color: "#D381C996"
      cardinalDecals:
        South: BrickTileWhiteLineS
        East: BrickTileWhiteLineE
        North: BrickTileWhiteLineN
        West: BrickTileWhiteLineW
      cornerDecals:
        SouthEast: BrickTileWhiteCornerSe
        SouthWest: BrickTileWhiteCornerSw
        NorthEast: BrickTileWhiteCornerNe
        NorthWest: BrickTileWhiteCornerNw
      pocketDecals:
        SouthWest: BrickTileWhiteInnerSw
        SouthEast: BrickTileWhiteInnerSe
        NorthWest: BrickTileWhiteInnerNw
        NorthEast: BrickTileWhiteInnerNe

# SalvageOutpost prototypes
- type: dungeonConfig
  id: LPPSalvageOutpost
  generator: !type:PrefabDunGen
    roomWhitelist:
      - LPPSalvageOutpost
    presets:
      - Bucket
      - Wow
      - SpaceShip
      - Tall
  postGeneration:
    - !type:CorridorPostGen
      width: 3

    - !type:DungeonEntrancePostGen
      count: 2

    - !type:RoomEntrancePostGen
      entities:
        - CableApcExtension
        - AirlockMiningGlassDungeon

    - !type:EntranceFlankPostGen
      entities:
        - GrilleDungeon
        - MiningWindowDungeon

    - !type:ExternalWindowPostGen
      entities:
        - GrilleDungeon
        - MiningWindowDungeon

    - !type:WallMountPostGen
      spawns:
        - id: RandomPosterLegit
          orGroup: content
        - id: ExtinguisherCabinetFilled
          prob: 0.2
          orGroup: content
        - id: RandomPainting
          prob: 0.05
          orGroup: content
        - id: DefibrillatorCabinetFilled
          prob: 0.1
          orGroup: content

    - !type:BoundaryWallPostGen
      tile: FloorSteel
      wall: WallSolid
      cornerWall: WallReinforced

    - !type:JunctionPostGen
      width: 1

    - !type:JunctionPostGen

    - !type:AutoCablingPostGen

    - !type:CornerClutterPostGen
      contents:
        - id: PottedPlantRandom
          amount: 1
    - !type:CorridorDecalSkirtingPostGen
      cardinalDecals:
        South: BrickTileWhiteLineS
        East: BrickTileWhiteLineE
        North: BrickTileWhiteLineN
        West: BrickTileWhiteLineW
      cornerDecals:
        SouthEast: BrickTileWhiteCornerSe
        SouthWest: BrickTileWhiteCornerSw
        NorthEast: BrickTileWhiteCornerNe
        NorthWest: BrickTileWhiteCornerNw
      pocketDecals:
        SouthWest: BrickTileWhiteInnerSw
        SouthEast: BrickTileWhiteInnerSe
        NorthWest: BrickTileWhiteInnerNw
        NorthEast: BrickTileWhiteInnerNe
