- type: entity
  id: LPPLockerSecEngFilled
  suffix: BrigTech, Filled
  parent: LPPLockerSecEng
  components:
  - type: StorageFill
    contents:
      - id: LPPClothingMilitaryWebbingSecEng
      - id: LPPClothingBackpackDuffelSecurityEngineer
      - id: ToolboxMechanicalFilled
      - id: LPPClothingOuterHardsuitSecurityEng
      - id: ClothingShoesBootsMag
      - id: OxygenTankFilled
      - id: JetpackSecurity
      - id: LPPHammer
      - id: RCD
      - id: RCDAmmo

- type: entity
  id: NFClosetBombFilled
  parent: ClosetBombFilled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      - id: Wirecutter
      - id: Screwdriver
      - id: Multitool

- type: entity
  id: NFLockerSecurityFilled
  parent: LockerSecurityFilled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBasic
      - id: ClothingOuterArmorBasic
