- type: job
  id: LPPSecurityEngineer
  name: job-name-security-enginer
  description: job-description-security-enginer
  playTimeTracker: LPPJobSecurityEnginer
  requirements:
    - !type:CharacterHeightRequirement
      min: 160
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 36000
    - !type:CharacterDepartmentTimeRequirement
      department: Engineering
      min: 72000
  startingGear: LPPSecurityEngineerGear
  icon: "LPPJobIconSecurityEnginer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
#  - Brig
  - Maintenance
  - External
  - Engineering
  - Atmospherics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: LPPSecurityEngineerGear
  equipment:
    jumpsuit: LPPClothingUniformJumpsuitSecEngineer
    back: LPPClothingBackpackSecurityEngineer
    shoes: LPPClothingShoesBootsJackSecEnginer
    eyes: LPPClothingEyesHudSecEng
    # gloves: ClothingHandsGlovesCombat
    id: LPPSecurityEngineerPDA
    ears: LPPClothingHeadsetSecurityEngineer
    belt: LPPClothingMilitaryWebbingSecEng
    socks: LPPClothingUnderSocksNorm
    underwear: LPPBoxer
  underwear: LPPBriefs
  breast: LPPBraAltWhite
  innerClothingSkirt: LPPClothingUniformJumpSkirtSecEngineer
  satchel: LPPClothingSatchelSecurityEngineer
  duffelbag: LPPClothingBackpackDuffelSecurityEngineer
