- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobMedicalBorg

- type: playTimeTracker
  id: JobCourier

# - type: playTimeTracker # LPP It's JobLPP–êdjutant
#   id: JobAdminAssistant
