name: Publish-lostparadise

concurrency:
  group: publish-lostparadise

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.6.0
      with:
        submodules: 'recursive'

    - name: Download parts
      run: |
        git clone ${{ secrets.HUB_SEC_TOKEN }}
        mv Secrets/_PrivateResources/_Private Resources/Prototypes/
        mv Secrets/_PrivateResources/PERSONAL Resources/Textures/
        mv Secrets/_PrivateShared Content.Shared/_PrivateShared
        mv Secrets/_PrivateServer Content.Server/_PrivateServer
        mv Secrets/_PrivateClient Content.Client/_PrivateClient

    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 8.0.100

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --platform linux-x64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Publish version
      run: Tools/publish_multi_request.py
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}

    - name: Publish changelog
      run: Tools/actions_changelogs_since_last_run.py
      env:
        CHANGELOG_DIR: ${{ vars.CHANGELOG_DIR }}
        CHANGELOG_WEBHOOK: ${{ secrets.CHANGELOG_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
