name: RSI Validator

on:
  push:
    branches: [ master, staging, trying ]
    paths:
      - '**.rsi/**'

jobs:
  validate_rsis:
    name: Validate RSIs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Download parts
        run: |
          git clone ${{ secrets.HUB_SEC_TOKEN }}
          mv Secrets/_PrivateResources/_Private Resources/Prototypes/
          mv Secrets/_PrivateResources/PERSONAL Resources/Textures/
          mv Secrets/_PrivateShared Content.Shared/_PrivateShared
          mv Secrets/_PrivateServer Content.Server/_PrivateServer
          mv Secrets/_PrivateClient Content.Client/_PrivateClient
      - name: Setup Submodule
        run: git submodule update --init
      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Install Python dependencies
        run: |
          pip3 install --ignore-installed --user pillow jsonschema --break-system-packages
      - name: Validate RSIs
        run: |
          python3 RobustToolbox/Schemas/validate_rsis.py Resources/
